### PR TITLE
Optionally load config file paths from environment

### PR DESCRIPTION
**Pull request by stevenzeiler**
This makes it easier to put configuration in a linux-standard place, or to link config files in via a docker container volume.

### CODE REVIEW

**Comment by brianvh** [comment]
Hey, Steven. Thanks for the PR! This looks good. We're still getting things setup for how we're going to handle contributions and the like, but your change should be the first community submission that we merge in.

**Comment by stevenzeiler** [comment]
@brianvh Do you guys have a Telegram group or something similar to collaborate?

**Comment by shphrd** [comment]
Hi @stevenzeiler! We just set up our [Gitter](https://gitter.im/hashrabbit/carrot-pool) room.

**Comment by brianvh** [comment]
Hi, Steven. Sorry for the delay in getting back to you. We've got a lot of balls in the air, with this new launch. I wanted to let you know that your PR hasn't fallen through the cracks. 😀

A couple of comments, based on your latest 2 commits:
* We're in the process of building "correct" sample configs (In fact, we merged something recently), along with more complete docs explaining what each of the config settings does. So, while you're corrected config is appreciated, we won't be accepting it as part of this PR/branch.
* Also, we use a combination of GitHub Actions, for our CI, along with CodeClimate for monitoring repo health and progress. We're not using something like CircleCi, since releases of `carrot-pool` aren't intended for Continuous Deployment.

If you'd like to fork the repo, and then make specific config and CI/CD alternations to your version, we think that's great. But, we need to keep the main `carrot-pool` as clean and agnostic as we can, so that any member of the community can download it, and make there own deployable release, with whatever toolchain they're using.

I'd still like to merge in your config file path from ENV commit, but I'd need you to remove the additional commits, which we won't be merging. Thanks! And please keep submitting PRs, or opening Issues for things you'd like to see changed, fixed, or added. We love the feedback and contributions.

**Pull request closed without merging**
