### PR TITLE
Update pool config sample

### PR DESCRIPTION
**Pull request by nealhhdotdev**
This should prevent some config related errors when using default values in the `pool_config_sample.json`.
Feel free to comment!

### CODE REVIEW

**Comment by brianvh** [comment]
The changes look good. Do we want to leave the fake coin in the sample, or set it to BTC? Maybe using an open BTC daemon setup?

This might be more than we want to do, just now, but I wanted to bring it up, since @shphrd mentioned not using the fake "Carrot" coin in the config sample.

**Comment by nealhhdotdev** [comment]
> The changes look good. Do we want to leave the fake coin in the sample, or set it to BTC? Maybe using an open BTC daemon setup?
> 
> This might be more than we want to do, just now, but I wanted to bring it up, since @shphrd mentioned not using the fake "Carrot" coin in the config sample.

That's a good idea for a future update.   Those values won't prevent normal operation/behavior, so, we've decided to leave them in place.

**Comment by shphrd** [comment]
LQTM 👍

**Comment by shphrd** [comment]
LGTM 👍

**Review by brianvh — APPROVED** [review]

**Pull request merged**
